# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 21:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFromRegister',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='UserFromLogIn',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('resultfromvalidation', django.db.models.manager.Manager()),
            ],
        ),
    ]
