# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20170529_2130'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
