# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20170531_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='exam_app.User')),
                ('users_who_liked', models.ManyToManyField(related_name='secrets_liked', to='exam_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='secrets',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='users',
        ),
        migrations.RemoveField(
            model_name='secrets',
            name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Secrets',
        ),
    ]
