# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20170531_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='users_who_liked',
            new_name='likers',
        ),
    ]
